version: '3.3'

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes:
            - ./app/public:/var/www/html/public:ro
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
        links:
            - phpfpm
    phpfpm:
        build:
            context: .
            dockerfile: docker_builds/Dockerfile.phpfpm-alpine
        ports:
            - "9000:9000"
        environment:
            - DB_HOST=mysql
            - DB_NAME=fuel
            - DB_USER=root
            - DB_PASS=root
        volumes:
            - ./app:/var/www/html:rw
        links:
            - mysql
    mysql:
        image: mariadb:10.3
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=fuel
        ports:
            - "3306:3306"
